import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6FBFC',
  },

  /* ---------------- Hero ---------------- */
  heroContainer: {
    height: 160,
    backgroundColor: '#088F9E',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    top:-50
  },
  heroOverlay: {
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 2 } },
      android: { elevation: 2 },
    }),
  },
  heroContent: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  backBtn: {
    position: 'absolute',
    top: 2,
    left: 16,
    padding: 8,
    backgroundColor: '#E8FFFE',
    borderRadius: 12,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#f4ffffff',
    marginLeft:45,
    top:-3,
       fontFamily: 'Nunito_700Bold',
  },
  heroSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#eaf5f8ff',
    opacity: 0.85,
     marginLeft:45,
    top:-10,
       fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- Search Row ---------------- */
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -22,
    paddingHorizontal: 16,
    gap: 8,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D9EFF1',
    height: 44,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    fontSize: 14,
    color: '#033D3F',
  },
  iconBtn: {
    paddingHorizontal: 12,
    height: 44,
    backgroundColor: '#0A5566',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaBtn: {
    paddingHorizontal: 14,
    height: 44,
    backgroundColor: '#10A6A6',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaBtnText: {
    color: '#fff',

    fontSize: 13,
       fontFamily: 'Nunito_700Bold',
  },
  aiBtn: {
    paddingHorizontal: 12,
    height: 44,
    backgroundColor: '#3CAEFF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  aiBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 12,
       fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- Chips ---------------- */
  chipsRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E8FFFE',
    borderWidth: 1,
    borderColor: '#BEECEF',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    marginRight: 8,
  },
  chipText: {
    color: '#0A5566',
    fontSize: 12,
    fontWeight: '700',
  },
  clearAllChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#0A5566',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  clearAllChipText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
       fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- List ---------------- */
  list: {
    marginTop: 6,
    paddingHorizontal: 16,
  },
  inlineLoader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: 10,
  },
  inlineLoaderText: {
    color: '#0A5566',
    fontSize: 12,
    fontWeight: '600',
       fontFamily: 'Nunito_700Bold',
  },
  loaderWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  loaderText: {
    marginTop: 8,
    color: '#0A5566',
    fontWeight: '700',
       fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- Tutor Card ---------------- */
  tutorCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E6F3F4',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 6, shadowOffset: { width: 0, height: 2 } },
      android: { elevation: 2 },
    }),
  },
  cardLeft: {
    paddingRight: 8,
    justifyContent: 'center',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#EEF8F8',
  },
  cardRight: {
    flex: 1,
    paddingLeft: 6,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  tutorName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    color: '#033D3F',
    marginRight: 8,
       fontFamily: 'Nunito_700Bold',
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF4DB',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#7A4A00',
       fontFamily: 'Nunito_400Regular',
  },
  subject: {
    fontSize: 13,
    color: '#0A5566',
    marginBottom: 6,
     fontFamily: 'Nunito_400Regular',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E8FFFE',
    borderColor: '#BEECEF',
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  metaText: {
    fontSize: 12,
    color: '#0A5566',
    fontWeight: '700',
     fontFamily: 'Nunito_400Regular',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryBtn: {
    flex: 1,
    backgroundColor: '#E3F8F8',
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#CFF0F1',
    borderWidth: 1,
  },
  secondaryBtnText: {
    color: '#0A5566',
    fontWeight: '800',
    fontSize: 12,
     fontFamily: 'Nunito_700Bold',
  },
  primaryBtn: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: '#0A5566',
    alignItems: 'center',
    justifyContent: 'center',
     fontFamily: 'Nunito_700Bold',
  },
  primaryBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 12,
     fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- Filters Sheet ---------------- */
  filterModal: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: -2 } },
      android: { elevation: 10 },
    }),
  },
  filterHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#033D3F',
     fontFamily: 'Nunito_700Bold',
  },
  label: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 6,
    marginTop: 12,
    color: '#0A5566',
     fontFamily: 'Nunito_700Bold',
  },
  input: {
    backgroundColor: '#F3FAFA',
    borderRadius: 12,
    padding: 12,
    borderColor: '#D6E0F5',
    borderWidth: 1,
    fontSize: 14,
     fontFamily: 'Nunito_700Bold',
  },
  dropdown: {
    backgroundColor: '#F3FAFA',
    borderColor: '#D6E0F5',
    borderRadius: 12,
  },
  dropdownBox: {
    borderColor: '#D6E0F5',
    borderRadius: 12,
  },
  dropdownText: { fontSize: 14, color: '#033D3F' ,  fontFamily: 'Nunito_400Regular',},
  dropdownLabel: { fontSize: 14, color: '#033D3F',  fontFamily: 'Nunito_400Regular', },
  filterActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  showButton: {
    flex: 1,
    backgroundColor: '#10A6A6',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  clearButton: {
    flex: 1,
    backgroundColor: '#E3EBFF',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    fontFamily: 'Nunito_700Bold',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '800',
    fontFamily: 'Nunito_700Bold',
  },
  clearButtonText: {
    color: '#0A5566',
    fontWeight: '800',
    fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- Empty State ---------------- */
  emptyWrap: {
    paddingTop: 40,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  emptyImg: {
    width: 120,
    height: 120,
    marginBottom: 10,
    opacity: 0.9,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#033D3F',
    marginBottom: 6,
    fontFamily: 'Nunito_700Bold',
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#0A5566',
    textAlign: 'center',
    lineHeight: 18,
    fontFamily: 'Nunito_700Bold',
  },

  /* ---------------- AI Modal ---------------- */
  aiModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  aiModal: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
  },
  aiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  aiTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#033D3F',
  },
  aiDesc: {
    fontSize: 13,
    color: '#0A5566',
    lineHeight: 18,
    fontFamily: 'Nunito_400Regular',
  },
  aiHintRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
    alignItems: 'center',
  },
  aiHintText: {
    fontSize: 12,
    color: '#0A5566',
    fontWeight: '700',
    fontFamily: 'Nunito_700Bold',
  },
  aiFooterRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  aiCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aiCheckText: {
    fontSize: 12,
    color: '#0A5566',
    fontWeight: '700',
    fontFamily: 'Nunito_700Bold',
  },
  aiCancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#E8FFFE',
    borderRadius: 10,
    borderColor: '#BEECEF',
    borderWidth: 1,
  },
  aiCancelText: {
    color: '#0A5566',
    fontWeight: '800',
    fontFamily: 'Nunito_700Bold',
  },
  aiContinueBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#0A5566',
    borderRadius: 10,
    fontFamily: 'Nunito_700Bold',
  },
  aiContinueText: {
    color: '#fff',
    fontWeight: '800',
    fontFamily: 'Nunito_700Bold',
  },
});

export default styles;
